name: Python Application CI

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Set your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure your requirements.txt is in the root directory

    - name: Run tests
      run: |
        # Add your testing commands here, e.g., pytest
        # echo "Run your tests here"

    - name: Package application
      run: |
        zip -r python-app.zip .  # Create a zip of your application

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: python-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EchoMind'  # Replace with your Azure App Service name
        package: './python-app.zip'  # Path to the downloaded artifact
